name: Build ffmpeg

on:
  workflow_dispatch:

concurrency: 
  group: build-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildt:
    if: github.actor != 'dependabot[bot]'
    
    runs-on: windows-2019

    steps:
      - name: Run build batchfile
        run: |
          cmd media-autobuild_suite.bat