name: Build ffmpeg

on:
  workflow_dispatch:

concurrency: 
  group: build-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ffmpeg:
    if: github.actor != 'dependabot[bot]'
    
    runs-on: windows-2019
    defaults:
      shell: cmd

    steps:
      - name: Run build batchfile
        run: |
          media-autobuild_suite.bat