name: Build ffmpeg

on:
  workflow_dispatch:

concurrency: 
  group: build-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ffmpeg:
    if: github.actor != 'dependabot[bot]'
    
    runs-on: windows-2019

    steps:
      - name: Install nVidia CUDA toolkit
        uses: Jimver/cuda-toolkit@master
        with:
          cuda: '11.1.1'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build batchfile
        run: |
          ./media-autobuild_suite.bat