name: Build ffmpeg

on:
  workflow_dispatch:

concurrency: 
  group: build-group-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-ffmpeg:
    if: github.actor != 'dependabot[bot]'
    
    runs-on: windows-2019

    steps:
      - name: Install nVidia CUDA toolkit
        uses: Jimver/cuda-toolkit@master
        with:
          method: 'network'
          cuda: '11.1.1'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run build batchfile
        run: |
          ./media-autobuild_suite.bat

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ffmpeg
          path: |
            ./local64/bin
            ./local64/bin-audio
            ./local64/bin-global
            ./local64/bin-video
